from django.conf import settings
OPEXA_BOOKS_ADMIN_USER_GROUP_NAME = getattr(settings, 'OPEXA_BOOKS_ADMIN_USER_GROUP_NAME',
    "Admin Users")
OPEXA_BOOKS_STANDARD_USER_GROUP_NAME = getattr(settings, 'OPEXA_BOOKS_STANDARD_USER_GROUP_NAME',
    "Standard User")
OPEXA_BOOKS_BLOCKCHAIN_NAME = getattr(settings, 'OPEXA_BOOKS_BLOCKCHAIN_NAME',
    "opexa_books")
OPEXA_BOOKS_BLOCKCHAIN_HOST = getattr(settings, 'OPEXA_BOOKS_BLOCKCHAIN_HOST',
    7557)
OPEXA_BOOKS_BLOCKCHAIN_PORT = getattr(settings, 'OPEXA_BOOOPEXA_BOOKS_BLOCKCHAIN_PORTKS_ADMIN_USER_GROUP_NAME',
    7557)
OPEXA_BOOKS_BLOCKCHAIN_RPC_PORT = getattr(settings, 'OPEXA_BOOKS_BLOCKCHAIN_RPC_PORT',
    8002)
OPEXA_BOOKS_BLOCKCHAIN_RPC_USER = getattr(settings, 'OPEXA_BOOKS_BLOCKCHAIN_RPC_USER',
    "multichainrpc")
OPEXA_BOOKS_BLOCKCHAIN_RPC_PASSWORD = getattr(settings, 'OPEXA_BOOKS_BLOCKCHAIN_RPC_PASSWORD',
    "r349kekoerto304t3904tik")