# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-20 19:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='JournalCreationRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_to_use', models.CharField(choices=[('D', 'Debit'), ('C', 'Credit')], max_length=1)),
                ('reverse_column', models.BooleanField()),
                ('include_credit_from', models.ManyToManyField(related_name='credit_included', to='books.Account')),
                ('include_debt_from', models.ManyToManyField(related_name='debt_included', to='books.Account')),
            ],
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('currency', models.CharField(choices=[('USD', 'USD')], max_length=3)),
                ('value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('approved', models.BooleanField()),
                ('credit_acc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_entry', to='books.Account', verbose_name='Account to credit')),
                ('credit_branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_branch', to='books.Branch')),
                ('debit_acc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debit_entry', to='books.Account', verbose_name='Account to debit')),
                ('debit_branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debit_branch', to='books.Branch')),
            ],
        ),
        migrations.CreateModel(
            name='JournalEntryAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('D', 'Debit'), ('C', 'Credit')], max_length=1)),
                ('perc', models.DecimalField(decimal_places=2, max_digits=15)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Account')),
                ('account_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='books.AccountType')),
            ],
        ),
        migrations.CreateModel(
            name='JournalEntryRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('display_template', models.TextField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='journalentryaction',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.JournalEntryRule'),
        ),
        migrations.AddField(
            model_name='account',
            name='account_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='books.AccountType'),
        ),
    ]
