# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-21 08:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalcreationrule',
            options={'verbose_name': 'Posting Rule', 'verbose_name_plural': 'Posting Rules'},
        ),
        migrations.RemoveField(
            model_name='journalentryaction',
            name='perc',
        ),
        migrations.AlterField(
            model_name='journalentryaction',
            name='account',
            field=models.ForeignKey(blank=True, help_text='Choose one of account type or specific account.', null=True, on_delete=django.db.models.deletion.CASCADE, to='books.Account', verbose_name='Specific account'),
        ),
        migrations.AlterField(
            model_name='journalentryaction',
            name='account_type',
            field=models.ForeignKey(blank=True, help_text='Choose one of account type or specific account.', null=True, on_delete=django.db.models.deletion.CASCADE, to='books.AccountType'),
        ),
    ]
