# Generated by Django 2.2.6 on 2019-10-18 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='account_type',
            new_name='account_group',
        ),
    ]
