# Generated by Django 2.2.6 on 2019-10-26 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accountgroup',
            unique_together={('name', 'system_account')},
        ),
    ]
