# Generated by Django 2.2.6 on 2019-10-18 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150)),
                ('credit_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credi_transaction_definitions', to='books.Account')),
                ('debit_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debit_transaction_definitions', to='books.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_transaction', to='books.SingleEntry')),
                ('debit_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debit_transaction', to='books.SingleEntry')),
                ('definition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.TransactionDefinition')),
            ],
        ),
    ]
