# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-21 12:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20170621_0800'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalentryrule',
            options={'verbose_name': 'Transaction Definition', 'verbose_name_plural': 'Transaction Definitions'},
        ),
        migrations.AddField(
            model_name='journalentry',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.JournalEntryRule'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='credit_acc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_entry', to='books.Account', verbose_name='credit'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='credit_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_branch', to='books.Branch', verbose_name='branch'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD')], default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='debit_acc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debit_entry', to='books.Account', verbose_name='debit'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='debit_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debit_branch', to='books.Branch', verbose_name='branch'),
        ),
    ]
