# Generated by Django 2.2.6 on 2020-01-23 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20200123_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='credit_entry',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='debit_entry',
        ),
        migrations.AddField(
            model_name='transaction',
            name='details',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
    ]
