# Generated by Django 2.2.6 on 2019-10-26 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20191026_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemaccount',
            name='initial_setup_done',
            field=models.BooleanField(default=False),
        ),
    ]
