# Generated by Django 2.2.6 on 2019-10-19 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20191019_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaredsource',
            name='credit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='declaredsource',
            name='debit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
