# Generated by Django 2.2.6 on 2020-01-23 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20200123_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='details',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
