# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-21 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20170621_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalcreationrule',
            name='multi_column',
            field=models.BooleanField(default=False),
        ),
    ]
