# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-21 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_journalcreationrule_multi_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalcreationrule',
            name='name',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
