# Generated by Django 2.2.6 on 2020-01-23 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20200123_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='singleentry',
            name='creator_ref',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
