# Generated by Django 2.2.6 on 2020-01-24 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_singleentry_creator_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoubleEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('details', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='singleentry',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Account'),
        ),
        migrations.AlterField(
            model_name='singleentry',
            name='action',
            field=models.CharField(choices=[('D', 'Debit'), ('C', 'Credit')], max_length=1),
        ),
        migrations.AlterField(
            model_name='singleentry',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='singleentry',
            name='double_entry',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.DoubleEntry'),
        ),
    ]
