# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-24 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_journalcreationrule_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='details',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='currency',
            field=models.CharField(choices=[(b'USD', b'USD')], default=b'USD', max_length=3, null=True),
        ),
    ]
