# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-24 19:47
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20170624_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='BooksOfficeSystem',
            fields=[
                ('system_code', models.CharField(default=uuid.uuid4, max_length=2000, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='currency',
            field=models.CharField(choices=[(b'USD', b'USD')], default=b'USD', max_length=3),
        ),
    ]
