# Generated by Django 2.2.6 on 2020-01-24 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20200124_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='doubleentry',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='books.Account'),
            preserve_default=False,
        ),
    ]
