# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-25 00:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20170624_2147'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BooksOfficeSystem',
            new_name='OpexaBooksSystem',
        ),
    ]
