# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-25 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20170625_0255'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalcreationrule',
            name='latest_pdf',
            field=models.FileField(editable=False, null=True, upload_to=b''),
        ),
    ]
