# Generated by Django 2.2.6 on 2020-01-24 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20200124_0051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doubleentry',
            name='details',
        ),
        migrations.RemoveField(
            model_name='doubleentry',
            name='value',
        ),
    ]
