# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-25 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_journalcreationrule_latest_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalcreationrule',
            name='column_to_use',
        ),
        migrations.RemoveField(
            model_name='journalcreationrule',
            name='reverse_column',
        ),
        migrations.AddField(
            model_name='journalcreationrule',
            name='reversed_credit_entries',
            field=models.ManyToManyField(help_text=b'Reversed entries will appear on the debit side of the journal.', related_name='reversed_credit_entries', to='books.Account'),
        ),
        migrations.AddField(
            model_name='journalcreationrule',
            name='reversed_debit_entries',
            field=models.ManyToManyField(help_text=b'Reversed entries will appear on the credit side of the journal.', related_name='reversed_debit_entries', to='books.Account'),
        ),
        migrations.AlterField(
            model_name='journalcreationrule',
            name='include_credit_from',
            field=models.ManyToManyField(help_text=b'Accounts from which to extract credit entries.', related_name='credit_included', to='books.Account'),
        ),
        migrations.AlterField(
            model_name='journalcreationrule',
            name='include_debt_from',
            field=models.ManyToManyField(help_text=b'Accounts from which to extract debt entries.', related_name='debt_included', to='books.Account'),
        ),
        migrations.AlterField(
            model_name='journalcreationrule',
            name='latest_pdf',
            field=models.FileField(null=True, upload_to=b'journal_pdfs'),
        ),
    ]
