# Generated by Django 2.2.6 on 2020-01-24 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_auto_20200124_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singleentry',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
