# Generated by Django 2.2.6 on 2020-01-24 01:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_auto_20200124_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singleentry',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 1, 24, 1, 10, 57, 947630, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
