# Generated by Django 2.2.6 on 2020-01-24 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_auto_20200124_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='doubleentry',
            name='details',
            field=models.CharField(default="Irene's Wages.", max_length=300),
            preserve_default=False,
        ),
    ]
