# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-28 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_auto_20170625_1932'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name_plural': 'Branches'},
        ),
        migrations.AlterModelOptions(
            name='journalentry',
            options={'verbose_name_plural': 'Journal entries'},
        ),
        migrations.AddField(
            model_name='journalcreationrule',
            name='preset',
            field=models.CharField(blank=True, choices=[(b'TB', b'Trial Balance'), (b'CB', b'Cash Book')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='journalcreationrule',
            name='latest_pdf',
            field=models.FileField(blank=True, null=True, upload_to=b'journal_pdfs'),
        ),
    ]
