# Generated by Django 2.2.6 on 2020-01-24 07:32

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_doubleentry_details'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doubleentry',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Double entries'},
        ),
        migrations.AlterModelOptions(
            name='singleentry',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Single entries'},
        ),
        migrations.AlterField(
            model_name='accountgroup',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='books.AccountGroup', verbose_name='parent account group'),
        ),
    ]
