# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-28 13:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_auto_20170628_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalcreationrule',
            name='after_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='journalcreationrule',
            name='before_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
