# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-15 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_auto_20170628_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalcreationrule',
            name='include_credit_from',
            field=models.ManyToManyField(help_text='Accounts from which to extract credit entries.', related_name='credit_included', to='books.Account'),
        ),
        migrations.AlterField(
            model_name='journalcreationrule',
            name='include_debt_from',
            field=models.ManyToManyField(help_text='Accounts from which to extract debt entries.', related_name='debt_included', to='books.Account'),
        ),
        migrations.AlterField(
            model_name='journalcreationrule',
            name='latest_pdf',
            field=models.FileField(blank=True, null=True, upload_to='journal_pdfs'),
        ),
        migrations.AlterField(
            model_name='journalcreationrule',
            name='preset',
            field=models.CharField(blank=True, choices=[('TB', 'Trial Balance'), ('CB', 'Cash Book')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='journalcreationrule',
            name='reversed_credit_entries',
            field=models.ManyToManyField(blank=True, help_text='Reversed entries will appear on the debit side of the journal.', related_name='reversed_credit_entries', to='books.Account'),
        ),
        migrations.AlterField(
            model_name='journalcreationrule',
            name='reversed_debit_entries',
            field=models.ManyToManyField(blank=True, help_text='Reversed entries will appear on the credit side of the journal.', related_name='reversed_debit_entries', to='books.Account'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD')], default='USD', max_length=3),
        ),
    ]
