# Generated by Django 2.2.6 on 2020-01-27 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_auto_20200124_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='doubleentry',
            name='related_document',
            field=models.FileField(blank=True, null=True, upload_to='double_entry_files'),
        ),
    ]
