# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-15 09:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_auto_20170715_0816'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=120)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('date_issued', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('buffer_days', models.IntegerField(default=7, verbose_name='Buffer')),
                ('max_value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Max Value ($)')),
                ('min_value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Min Value ($)')),
                ('establishment_fee_rate', models.DecimalField(decimal_places=4, max_digits=7, verbose_name='Establishment Fee (%)')),
                ('roll_over_fee_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='Rollover Fee (%)')),
                ('default_fee_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='Default Fee (%)')),
                ('discount_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Discount Rate (%)')),
                ('rollover_discount_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Rollover Discount Rate (%)')),
                ('default_discount_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Default Discount Rate (%)')),
                ('pdf_version', models.FileField(blank=True, null=True, upload_to='pdf_termsheets/')),
                ('deal_settlement_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Account')),
            ],
            options={
                'verbose_name_plural': 'Term Sheets',
                'verbose_name': 'Term Sheet',
            },
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='upload_docs')),
            ],
        ),
        migrations.AddField(
            model_name='termsheet',
            name='guarantee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ts_guarantee', to='books.Upload'),
        ),
        migrations.AddField(
            model_name='termsheet',
            name='recourse_measures',
            field=models.ManyToManyField(blank=True, related_name='ts_recourse', to='books.Upload'),
        ),
        migrations.AddField(
            model_name='termsheet',
            name='security',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ts_security', to='books.Upload'),
        ),
    ]
