# Generated by Django 2.2.6 on 2020-01-31 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_doubleentry_related_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='doubleentry',
            name='creator_ref',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
