# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-15 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_auto_20170715_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='termsheet',
            name='interest_method',
            field=models.CharField(choices=[('S', 'Straight'), ('C', 'Compound')], default='S', max_length=2),
        ),
    ]
