# Generated by Django 3.1 on 2020-09-11 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_auto_20200204_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemaccount',
            name='password',
        ),
        migrations.AlterField(
            model_name='systemaccount',
            name='email',
            field=models.EmailField(blank=True, help_text='Used for reporting \n        and data recovery.', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='systemaccount',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('system_account', 'code')},
        ),
    ]
