# Generated by Django 3.1 on 2020-09-14 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_auto_20200911_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='address_id',
            field=models.CharField(blank=True, editable=False, max_length=120, null=True),
        ),
    ]
