# Generated by Django 3.1 on 2020-09-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_account_address_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='increase_balance',
            field=models.CharField(choices=[('', 'None'), ('D', 'Debit'), ('C', 'Credit')], default='', max_length=1),
        ),
    ]
