# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-15 10:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0019_journalentryrule_term_sheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termsheet',
            name='guarantee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ts_guarantee', to='books.Upload'),
        ),
        migrations.AlterField(
            model_name='termsheet',
            name='security',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ts_security', to='books.Upload'),
        ),
    ]
