# Generated by Django 3.1 on 2020-09-19 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0019_account_increase_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemaccount',
            name='settings',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.accountsettings'),
        ),
    ]
