# Generated by Django 3.1 on 2020-09-19 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0020_auto_20200919_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='address_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
