# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-15 10:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0020_auto_20170715_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='termsheet',
            name='deal_settlement_account',
        ),
    ]
