# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-15 10:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0021_remove_termsheet_deal_settlement_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='credit_acc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_entry', to='books.Account', verbose_name='credit'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD')], default='USD', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='debit_acc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debit_entry', to='books.Account', verbose_name='debit'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
    ]
