# Generated by Django 3.0.6 on 2020-11-09 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0021_auto_20200919_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='system_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.SystemAccount'),
        ),
    ]
