# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-18 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0023_auto_20170715_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='term',
            field=models.FloatField(help_text='In Days', null=True),
        ),
        migrations.AlterField(
            model_name='termsheet',
            name='default_discount_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Monthly Default Discount Rate (%)'),
        ),
        migrations.AlterField(
            model_name='termsheet',
            name='discount_rate',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Monthly Discount Rate (%)'),
        ),
        migrations.AlterField(
            model_name='termsheet',
            name='rollover_discount_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Monthly Rollover Discount Rate (%)'),
        ),
    ]
