# Generated by Django 3.0.6 on 2020-12-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0024_auto_20201109_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='details',
            field=models.TextField(default='', max_length=2000),
            preserve_default=False,
        ),
    ]
