# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-18 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0025_account_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.Account', verbose_name='Group Account Under'),
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='credit_acc',
        ),
        migrations.AddField(
            model_name='journalentry',
            name='credit_acc',
            field=models.ManyToManyField(related_name='credit_entry', to='books.Account', verbose_name='credit'),
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='debit_acc',
        ),
        migrations.AddField(
            model_name='journalentry',
            name='debit_acc',
            field=models.ManyToManyField(related_name='debit_entry', to='books.Account', verbose_name='debit'),
        ),
    ]
