# Generated by Django 3.0.6 on 2020-12-15 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0025_auto_20201205_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='details',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
