# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-01 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0028_auto_20170730_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.Account', verbose_name='Type'),
        ),
        migrations.RemoveField(
            model_name='journalentryaction',
            name='account',
        ),
        migrations.AddField(
            model_name='journalentryaction',
            name='account',
            field=models.ManyToManyField(blank=True, help_text='Choose one of account type or specific account.', to='books.Account', verbose_name='Specific account'),
        ),
    ]
