# Generated by Django 3.1.7 on 2021-02-25 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0028_auto_20210223_0842'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingTier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('charge', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='billingaccount',
            name='charge',
        ),
        migrations.AddField(
            model_name='billingaccount',
            name='billing_tier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.billingtier'),
        ),
    ]
