# Generated by Django 3.1.7 on 2021-02-26 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0030_auto_20210225_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingmethod',
            name='billing_period',
            field=models.IntegerField(default=1),
        ),
    ]
