# Generated by Django 3.1.7 on 2021-02-26 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0031_auto_20210226_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaccount',
            name='next_billed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
