# Generated by Django 3.1.7 on 2021-02-26 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0032_billingaccount_next_billed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaccount',
            name='next_billed',
            field=models.DateField(blank=True, null=True),
        ),
    ]
