# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-01 19:35
from __future__ import unicode_literals

import books.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0033_auto_20170801_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalcreationrule',
            name='default',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='journal',
            name='date_from',
            field=models.DateField(default=books.models.year_ago),
        ),
        migrations.AlterField(
            model_name='journal',
            name='date_to',
            field=models.DateField(default=books.models.today),
        ),
        migrations.AlterField(
            model_name='journal',
            name='preset',
            field=models.CharField(blank=True, choices=[('TB', 'Trial Balance'), ('BS', 'Balance Sheet'), ('CB', 'Cash Book')], help_text='Use system defined preset rule.', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='rule',
            field=models.ForeignKey(blank=True, help_text='Custom user defined rule.', null=True, on_delete=django.db.models.deletion.CASCADE, to='books.JournalCreationRule'),
        ),
    ]
