# Generated by Django 3.1.7 on 2021-02-26 01:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0033_auto_20210226_0241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='value',
        ),
        migrations.AddField(
            model_name='invoice',
            name='date',
            field=models.DateField(default=datetime.date(2021, 2, 26)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='entries',
            field=models.JSONField(default='{}', help_text='A list of dictionaries with the following keys: description, quantity, unit_price, total'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='books/generated/invoices'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
