# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-02 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0034_auto_20170801_1935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journalcreationrule',
            old_name='after_date',
            new_name='from_date',
        ),
        migrations.AlterField(
            model_name='journalcreationrule',
            name='include_credit_from',
            field=models.ManyToManyField(blank=True, help_text='Accounts from which to extract credit entries.', related_name='credit_included', to='books.Account'),
        ),
        migrations.AlterField(
            model_name='journalcreationrule',
            name='include_debt_from',
            field=models.ManyToManyField(blank=True, help_text='Accounts from which to extract debt entries.', related_name='debt_included', to='books.Account'),
        ),
    ]
