# Generated by Django 3.1.7 on 2021-02-26 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0034_auto_20210226_0333'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingmethod',
            name='days_till_due',
            field=models.IntegerField(default=30),
        ),
    ]
