# Generated by Django 3.1.7 on 2021-02-26 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0035_billingmethod_days_till_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaccount',
            name='product_description',
            field=models.CharField(default='Services Rendered.', help_text='What the user will be billed for (appears in description of invoice)', max_length=100),
            preserve_default=False,
        ),
    ]
