# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-02 12:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0036_auto_20170802_1226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journalcreationrule',
            old_name='before_date',
            new_name='date_to',
        ),
    ]
