# Generated by Django 3.1.7 on 2021-02-26 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0036_billingaccount_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingtier',
            old_name='charge',
            new_name='unit_price',
        ),
    ]
