# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-02 12:27
from __future__ import unicode_literals

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0037_auto_20170802_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalcreationrule',
            name='date_from',
            field=models.DateField(default=books.models.year_ago),
        ),
        migrations.AlterField(
            model_name='journalcreationrule',
            name='date_to',
            field=models.DateField(default=books.models.today),
        ),
    ]
