# Generated by Django 3.1.7 on 2021-02-28 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0037_auto_20210226_0444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='billing_account',
        ),
        migrations.AddField(
            model_name='invoice',
            name='billing_accounts',
            field=models.ManyToManyField(blank=True, to='books.BillingAccount'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='entries',
            field=models.JSONField(help_text='A list of dictionaries with the following keys: description, quantity, unit_price, total, billing_account'),
        ),
    ]
