# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-02 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0038_auto_20170802_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='date_from',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='date_to',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='preset',
        ),
        migrations.AlterField(
            model_name='journalcreationrule',
            name='preset',
            field=models.CharField(choices=[('TB', 'Trial Balance'), ('BS', 'Balance Sheet'), ('CB', 'Cash Book')], max_length=2, null=True),
        ),
    ]
