# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-02 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0040_auto_20170802_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentryaction',
            name='account_type',
        ),
        migrations.AddField(
            model_name='journalentryaction',
            name='account_type',
            field=models.ManyToManyField(blank=True, help_text='Choose one of account type or specific account.', to='books.AccountType'),
        ),
        migrations.RemoveField(
            model_name='journalentryaction',
            name='sub_type',
        ),
        migrations.AddField(
            model_name='journalentryaction',
            name='sub_type',
            field=models.ManyToManyField(blank=True, to='books.AccountSubType'),
        ),
    ]
