# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-03 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0041_auto_20170802_1302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='accountsubtype',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='accounttype',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='singleentry',
            options={'ordering': ['-journal_entry__date'], 'verbose_name_plural': 'Single Entries'},
        ),
        migrations.AddField(
            model_name='journalentryrule',
            name='allow_single_entry',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Describes the account under which this particular one is grouped.', null=True, on_delete=django.db.models.deletion.CASCADE, to='books.Account', verbose_name='Grouped under'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='rule',
            field=models.ForeignKey(blank=True, help_text='Please select a rule, then save and continue.', null=True, on_delete=django.db.models.deletion.CASCADE, to='books.JournalEntryRule'),
        ),
    ]
