# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-23 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0042_auto_20170803_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentryrule',
            name='allow_single_entry',
            field=models.BooleanField(default=False, help_text=b'If selected, system will no longer force debit and credit totals to match.'),
        ),
    ]
