# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-14 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0043_auto_20170823_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentryrule',
            name='allow_single_entry',
            field=models.BooleanField(default=False, help_text='If selected, system will no longer force debit and credit totals to match.'),
        ),
    ]
